version: "2"
services:
  onlyoffice:
    container_name: onlyoffice
    image: alehoho/oo-ce-docker-license
    environment:
      - JWT_ENABLED=yes
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=NCAuth  # custom auth header, needs to be defined in Nextcloud's config.php (https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/278)
    volumes:
      # Use system fonts 
      # - /usr/share/fonts:/usr/share/fonts:ro
      # Place custom fonts here 
      - fonts:/usr/share/fonts/truetype/custom
      - logs:/var/log/onlyoffice
      - data:/var/www/onlyoffice/Data
      - config:/etc/onlyoffice
    network_mode: bridge
    ports:
      - "8088:80"
    logging:
      driver: syslog
      
volumes:
   fonts:
   logs:
   data:
   config:
   