version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
       - "127.0.0.1:3012:3012"
       - "127.0.0.1:8888:80"
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - vaultwarden:/data
#  Relies on host level Apache2 HT   TP reverse proxy
#   caddy:
#     image: caddy:2
#     container_name: caddy
#     restart: always
#     ports:
#       - 80:80  # Needed for the ACME HTTP-01 challenge.
#       - 443:443
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile:ro
#       - caddy-config:/config
#       - caddy-data:/data
#     environment:
#       - DOMAIN=${YOUR_DOMAIN}  # Your domain.
#       - EMAIL=${YOUR_EMAIL} # admin@example.com                 # The email address to use for ACME registration.
#       - LOG_FILE=/data/access.log
volumes:
   vaultwarden:
#   caddy-data:
#   caddy-config:

   